### ISSUE TITLE
Allow users to add reference types, similar to RefToolbar

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#100]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 22, 2011 19:46:30_

RefToolbar has a facility ( http://en.wikipedia.org/wiki/Wikipedia:RefToolbar_2.0#Sample_code ) for adding template types dynamically.

We should consider either implementing a similar mechanism, or sharing and/or collaborating with RefToolbar on this.  This is an important issue, because the templates are constantly changing, but key to the functionality of both scripts.

From what I can tell, ProveIt's description mechanism is more elaborate, since it keeps track of both required and default parameters.  However, there could still be a way to have bare-bones reference subclasses that lack this information.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=101_

**Comment by sophivorus** [comment]
This is now obsolete. The list of references should be extracted directly from the wiki where ProveIt is running, and the list of parameters, from the TemplateData.
