### ISSUE TITLE
Skin.js link doesn't work on all Wikipedias

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#101]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 22, 2011 20:59:44_

Links like http://lang.wikipedia.org/wiki/Special:MyPage/skin.js?action=edit do not seem to work on all Wikipedias.  In particular, it does not work on the Chinese one ( http://zh.wikipedia.org/wiki/Special:MyPage/skin.js?action=edit ).  The skin.js part doesn't redirect.

Since this is site-specific, we need to figure out another way of linking to these pages.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=102_

**Comment by sophivorus** [comment]
How is this a ProveIt issue?
