### ISSUE TITLE
ProveIt can cover Firefox find bar

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#103]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 26, 2011 18:33:24_

ProveIt can sometimes cover the Firefox find bar.  I have noticed this in the past, and it was reported by AdeMiami on our talk page:

"In Firefox 3.6.13, on Mac system 10.4.11, as I type Command-G to repeat a search for a text string, the highlighted text is right at the bottom of the edit window, where it is "covered" by Proveit, even when minimized. It would be desirable to be able to hide Proveit completely to get round this—it's tiresome to have to change your preferences every time you want to either search for something or reference something, tasks which are often simultaneous anyway."
---
A possible solution is to allow completely hiding ProveIt as discussed in issue 93 .

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=104_

**Comment by sophivorus** [comment]
ProveIt can be hidden by clicking on the button in the toolbar. Should we close this?

**Comment by Sophivorus** [comment]
As I said above, ProveIt can be hidden by clicking the button in the toolbar (but see #226). Also, Firefox 3.0 is extremely old now (we're in 48.0) and the current versions highlight the results of the find bar in the center of the page.
