### ISSUE TITLE
Support cite doi

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#104]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 26, 2011 18:39:17_

Smith609 requested on our talk page that we add support for cite doi.

This just requires following the steps at NewCiteType .

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=105_

**Comment by sophivorus** [comment]
The Template:Cite doi is deprecated, so support is no longer desirable.
