### ISSUE TITLE
Use existing accessdate format for auto-fill

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#108]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on April 04, 2011 22:22:09_

ProveIt auto-fills the access date fields for the user's convenience.  To comply with http://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style_&#37;28dates_and_numbers&#37;29#Format_consistency , it should use the article's existing reference format:

"Access and archive dates in references should be in either the reference format, or YYYY-MM-DD"

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=109_

**Comment by Sophivorus** [comment]
See #231
