### ISSUE TITLE
full ref name & details entered into Proveit generates a raw url

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#111]
_From [arbortender](https://code.google.com/u/112880040180406467569/) on June 30, 2011 14:36:48_

What steps will reproduce the problem? 1.First time using Proveit, have not attempted another yet
2.Opened proveit tab
3.entered all info from googlebooks about this book, including a refname
4.populated the references tab, and it showed all the details I entered
5.saved page, and got instead a raw reference at the citation What is the expected output? What do you see instead? expected fully detailed citation; got only raw citation of googlebooks url What version of the product are you using? On what operating system? OS WinXP, Browser Firefox5.0, don't know how to check the version of Proveit: not readily discernible. Please provide any additional information below. Page I was working on was [[Fred Lieberman]], at the citation for one of his own books, for which I was creating a cite (currently #7) in the reflist.  I'll leave it as-is for now, so you can see what I wound up with, but I need to fix it.
Thanks
Pat

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=112_

**Comment by Sophivorus** [comment]
The current code is too different from the old and more stable, it is very likely that this is no longer an issue, and anyway I'm unable to reproduce it. Pleas reopen this issue only if clear instructions on how to reproduce the issue can be given.
