### ISSUE TITLE
Make it easy for users to check version of ProveIt

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#112]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on June 30, 2011 20:41:33_

It is currently not practical for users to check which version of ProveIt they are using.  There should be a simple part of the UI that can show the commit id for easy copying.

This can be implemented by modifying the build script.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=113_

**Comment by lfschenone** [comment]
This is to facilitate bug reporting?

**Comment by lfschenone** [comment]
If we host the code at Commons (issue #219) then all users will use the same version of ProveIt, so by knowing the date of the report, we can know the version of the gadget.

**Comment by Sophivorus** [comment]
Code is now served from Commons.
