### ISSUE TITLE
Support Template:Allmusic references

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#114]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on July 16, 2011 21:56:44_

Bulldog73 suggested ( http://en.wikipedia.org/w/index.php?title=User_talk:ProveIt_GT&diff=439849744&oldid=430667567 ) supporting the Allmusic template.

Since this is neither a Cite nor Citation template, it would probably require a new subclass of AbstractReference, along with appropriate GUI changes.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=116_

**Comment by sophivorus** [comment]
Done!
