### ISSUE TITLE
Misplaced display of entire ProveIt interface

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#115]
_From [saeed.veradi](https://code.google.com/u/114898669025494416993/) on August 09, 2011 22:05:19_

What steps will reproduce the problem? 1. Go to Wikipedia
2. Click on "edit". What is the expected output? What do you see instead? https://skydrive.live.com/#cid=300CC2296DC3BCF2&id=300CC2296DC3BCF2&#37;21135 What version of the product are you using? On what operating system? I'm just using Wikipedia on Windows. Please provide any additional information below. I use many gadgets and Chrome. but even when I turn them off and use firefox, It's still exactly the same.

**Attachment:** [ProveIt.jpg ProveIt 2.jpg](http://code.google.com/p/proveit-js/issues/detail?id=117)

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=117_

**Comment by sophivorus** [comment]
This issue is too old to be relevant, the current version of the gadget is too different from the one that caused the bug.
