### ISSUE TITLE
Reference doesn't insert

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#116]
_From [vimaleshvara](https://code.google.com/u/112262251653094255251/) on August 16, 2011 11:28:42_

What steps will reproduce the problem? 1.opening proveit
2.while using proveit, re-entering the wiki edit
3. Returning to proveit, finishing form filing, attempting to insert the ref

What is the expected output?
that the coded ref is inserted

 What do you see instead?
instead nothing goes into the wiki edit page

What version of the product are you using?
recent...

On what operating system?
on Win 7 Please provide any additional information below.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=118_

**Comment by sophivorus** [comment]
This refers to the previous version of the gadget. The new version is too different for this report to be relevant. I haven't noticed any problems similar to the one reported in the latest version.
