### ISSUE TITLE
Add support for Cite magazine

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#117]
_From [s.vanslyck723](https://code.google.com/u/100799781273068478736/) on September 08, 2011 19:18:26_

What steps will reproduce the problem? 1. Enter a journal reference 2. 3. What is the expected output? What do you see instead? The name of the magazine's name should be included in the resulting reference, but it does not appear. What version of the product are you using? On what operating system? Ver. nknown. XP Pro, SP3 with all updates. Please provide any additional information below. See footnote to Cy Young at http://en.wikipedia.org/wiki/List_of_Freemasons

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=119_

**Comment by lfschenone** [comment]
A template called "Cite magazine" is now available (https://en.wikipedia.org/wiki/Template:Cite_magazine) so I renamed this issue to "Add support for Cite magazine".

**Comment by sophivorus** [comment]
Done thanks to TemplateData.
