### ISSUE TITLE
Rendering problems in IE 9

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#119]
_From [mflaschen@entech.com](https://code.google.com/u/117819889219415171362/) on November 18, 2011 19:22:31_

C628 reported the below on ProveIt's talk page on September 25, 2011:

"A few days ago, ProveIt started formatting itself rather badly in IE9; it would appear in the upper left hand corner of the screen, and then when I went to add a reference it would spew a lot of badly formatted crud all over the page."

The screenshot he linked is attached.

**Attachment:** [w0Hd1 - Imgur.png](http://code.google.com/p/proveit-js/issues/detail?id=121)

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=121_

**Comment by lfschenone** [comment]
Probably not an issue with the latest version, but can't check.
