### ISSUE TITLE
Support for creating Template:Citation

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#12]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on August 07, 2010 13:52:01_

The ProveIt GUI does not currently support Template:Citation ( http://en.wikipedia.org/wiki/Template:Citation ), though the backend code still does.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=12_

**Comment by lfschenone** [comment]
The Citation template is now supported. :-)

**Comment by mattflaschen** [comment]
This is a nice part of the rewrite.  Thanks again. :)
