### ISSUE TITLE
Update cite AV media (formerly cite video)

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#120]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on November 18, 2011 19:25:54_

Support the new cite video ( http://en.wikipedia.org/wiki/Template:Cite_video ) parameters.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=122_

**Comment by lfschenone** [comment]
Added the full parameter list.
