### ISSUE TITLE
Provit *displays* the fields in title case, e.g. Author, Publisher, even though they are really in lower case in the template. When I add new fields, I thus incorrectly use title case.

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#122]
_From [glass.ssalg](https://code.google.com/u/116778073544744638759/) on December 08, 2011 08:31:15_

What steps will reproduce the problem?
1. Add a new field via the "new field" button, with uppercase letters in the field name. For example, insert Last1 and First1.
2. Insert the template into the form.

What is the expected output? What do you see instead?
The capitalized user-added fields do not show in the rendered Wikipedia page.
The user-added fields *have not* been converted to lower case, as the template most usually demands. The original fields presented by Proveit *have* been converted to lower case.  

-- This problem arises because Proveit *displays* its fields in Title case, even though they are really lowercase in the form. When I insert new fields, I unconsciously follow the style that is in front of me.

When were you using ProveIt? On what browser (including version) and operating system?
I don't think this is browser specific, but I use Opera 11.5x on Linux.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=124_

**Comment by sophivorus** [comment]
This issue is obsolete, now that we use TemplateData to get the list of parameters.
