### ISSUE TITLE
does not work on pl-wiki

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#123]
_From [darjem](https://code.google.com/u/102331416920224599028/) on December 11, 2011 09:30:25_

From 2 different computers (5 different browsers) I can't make the script work on pl-wiki, while it works perfectly fine on en-wiki.

I would expect to see prove-it toolbar, but it does not show up at all. 

I don't think it is browser related, since it works for en-wiki and doesn't for pl-wiki, and is consistent across browsers. 

I followed the installation instructions for pl-wiki as acurately as I can imagine. 

My username is pundit.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=125_

**Comment by lfschenone** [comment]
Tested the latest version, works fine. See my common.js and common.css for the proper way to do it:
https://pl.wikipedia.org/wiki/Wikipedysta:Luis_Felipe_Schenone/common.js
https://pl.wikipedia.org/wiki/Wikipedysta:Luis_Felipe_Schenone/common.css
