### ISSUE TITLE
Add concept of parameter names mapping to canonical ones

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#124]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 27, 2012 21:26:00_

In some cases, multiple parameter names map to a single canonical parameter.  For example, with cite news, 'journal', 'magazine', 'periodical', and 'work' all map to 'newspaper'.  This is specific to each type (e.g. news).

This will improve the usability for  both the required and default features.  Required parameters will only be flagged as missing if they are still missing after canonicalization.  Default parameters should not included in the edit box if an equivalent one is already there.  For example, 'work' should not be shown if 'newspaper' or 'periodical' is already filled in.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=126_

**Comment by lfschenone** [comment]
The 'alias' parameter in the template definitions already covers this request. However, the gadget doesn't enforce required parameters yet, nor does it mark required parameters as such in the UI.

**Comment by lfschenone** [comment]
I'm closing this and creating another issue for the remaining features.
