### ISSUE TITLE
Centralize CiteReference per-type configuration

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#126]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 02, 2012 01:19:23_

Centralize the per-type configuration in CiteReference.  Rather than having separate default, required, icon, etc, put them in a single object indexed by type then other information.  E.g.:

var configuration = 
{
   web:
   {
     default: [],
     required: [],
     icon: ''
   },
   // ...
}

This will simplify adding new types ( http://code.google.com/p/proveit-js/wiki/NewCiteType ), and may not even affect the CiteReference API.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=128_

**Comment by lfschenone** [comment]
This seems outdated given the latest version, correct?

**Comment by mattflaschen** [comment]
Yes
