### ISSUE TITLE
Populate LANG from user preferences language

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#127]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 02, 2012 21:18:59_

Use the user preferences language:

mw.user.options.get('language')

if ProveIt has a localization for it.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=130_

**Comment by lfschenone** [comment]
This issue depends on issue 169.

**Comment by sophivorus** [comment]
Done!
