### ISSUE TITLE
Add support for Cite IETF and all redirects

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#129]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 16, 2012 21:57:41_

Add cite IETF and all redirects to it (including "RFC", "ietf", and "rfc").

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=132_

**Comment by sophivorus** [comment]
Support can be added as soon as <templatedata> is added to the docs.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148212
