### ISSUE TITLE
Invalid reference should not result in errors in makeRef, but they should be logged

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#130]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 21, 2012 16:53:23_

<ref>{{cite news | http://www.vg.no/nyheter/utenriks/artikkel.php?artid=10079661</ref> is interpreted as a cite, but it's invalid, which causes a null dereference.  This error in turn causes ProveIt to abort.

Invalid input should not cause a library error, and should be logged.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=133_

**Comment by Sophivorus** [comment]
The current version interprets
````
<ref>{{cite news | http://www.vg.no/nyheter/utenriks/artikkel.php?artid=10079661</ref>
````
as a raw reference, which I think is optimal.
