### ISSUE TITLE
Add editing for Vancouver style Template:vcite citations

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#132]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 21, 2012 23:30:01_

Add support for the Template:vcite citations (e.g. vcite book) from the Vancouver family. Citation Style Vancouver has two families of templates (vancite is the other, see issue https://github.com/proveit-js/proveit/issues/133) but vcite is generally preferred.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=135_

**Comment by sophivorus** [comment]
I'm generalising the title of #133 to cover both issues.
