### ISSUE TITLE
Add support for Vancouver style citations

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#133]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 21, 2012 23:34:54_

Add editing support for the Vancouver style citations (Vancite and Vcite templates). See http://en.wikipedia.org/wiki/Help:Citation_Style_Vancouver

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=136_

**Comment by sophivorus** [comment]
Support for this now depends on the <templatedata> tag being added to the documentation of the Vancouver style templates.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148213
