### ISSUE TITLE
Consider allowing inserting ref names for references in another section

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#135]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 29, 2012 16:43:13_

When editing a section, there is no way to insert ref names to references in another section.  This is because ProveIt has only parsed the wikitext in the current section.

Consider allowing this.  This would probably require loading and parsing the full wikitext of the page in the background, which will be a performance hit (it could possibly be done only for smaller pages).

This was brought up by AnkhMorpork on my talk page:

"One question: if you want to insert a ref name into a body of text that refers to a reference in a different section, how should you go about doing that?"

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=138_

**Comment by sophivorus** [comment]
Loading the wikitext in the background would be a performance hit, but it would only be done when a section is being edited and not the full text, so in many cases, there will be no performance hit.

**Comment by sophivorus** [comment]
However, loading all references when editing a section may be confusing, and rarely useful! Is it really worth it?

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148214
