### ISSUE TITLE
Merge in Farsi localization

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#137]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 31, 2012 00:17:42_

Mjbmr, a Farsi Wikipedia user, created a Farsi localization ( http://fa.wikipedia.org/wiki/&#37;D9&#37;85&#37;D8&#37;AF&#37;DB&#37;8C&#37;D8&#37;A7&#37;D9&#37;88&#37;DB&#37;8C&#37;DA&#37;A9&#37;DB&#37;8C:Gadget-ProveIt.js ) for ProveIt, including translations (including some things that were not yet keyed in the English version), a logo, and Farsi template parameters.

Some of this is easier to merge than other parts.  ProveIt should make it easier to do these per-Wikipedia localizations ( issue 139 ), as well as continue to support a user interface language different from the main Wikipedia language (see issue 130 ).

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=140_

**Comment by Sophivorus** [comment]
ProveIt has been fully internationalized now, but I'm afraid that it has also changed so much that this localization is no longer useful and it will be easier to start the Farsi localization from zero.
