### ISSUE TITLE
Add French Wikipedia localization

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#138]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 31, 2012 00:56:50_

Add a localization for French Wikipedia.  There seems to be significant interest ( http://fr.wikipedia.org/wiki/Wikip&#37;C3&#37;A9dia:Sondage/Int&#37;C3&#37;A9gration_du_gadget_ProveIt_dans_la_Wikip&#37;C3&#37;A9dia_francophone ).  There is an import at http://fr.wikipedia.org/wiki/MediaWiki:Gadget-ProveIt.js

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=141_

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148218
