### ISSUE TITLE
Redirect shorthand doesn't work

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#139]
_From [vimaleshvara](https://code.google.com/u/112262251653094255251/) on April 30, 2012 05:31:18_

What steps will reproduce the problem?
eg [[In Our Time (BBC Radio 4)|]] in the publisher field not=[[In Our Time (BBC Radio 4)|In Our Time]] as it would within the article

What is the expected output? What do you see instead?
In the reference:
Expected: In Our Time
Instead: [[In Our Time (BBC Radio 4)|]]

When were you using ProveIt? On what browser (including version) and operating system?
Windows 7, Firefox 11.0

If page-specific, what article were you editing?
It's happened on many pages, though I think it used to work OK (till when I'm not sure)

Optionally, what is your Wikipedia username?
DadaNeem

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=142_

**Comment by sophivorus** [comment]
I don't understand this issue. Can someone explain it in clearer terms?

**Comment by Sophivorus** [comment]
Showing the exact wikitext is the desired behavior.
