### ISSUE TITLE
Installation on German Wiki user account didn't work 

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#140]
_From [nota@schachenmayr.net](https://code.google.com/u/103569600024171637588/) on May 14, 2012 11:10:39_

I use Google Chrome 18.0.1025.168 What is the expected output? What do you see instead? take a look at: http://de.wikipedia.org/wiki/Benutzer:Melchior2006/skin.js Please provide any additional information below. You can mail me at nota@schachenmayr.net

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=143_

**Comment by sophivorus** [comment]
This refers to the previous version. The new version is too different for this report to be relevant. However, there's still no localisation to German, so although the gadget should work, all the messages will be in English (the fallback language).
