### ISSUE TITLE
Proveit vanishes when on pages "Articles_for_creation"

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#141]
_From [saddharmap](https://code.google.com/u/109245526605471033631/) on May 29, 2012 07:04:40_

What steps will reproduce the problem? 1. Does not work on pages "Articles_for_creation". 2. 3. What is the expected output? What do you see instead? The prove it tool is just not there. When were you using ProveIt? On what browser (including version) and operating system? Run in FF12 on Linux + Chromium + Konqueror If page-specific, what article were you editing? Occurs on all pages "Articles_for_creation"
Wikipedia_talk:Articles_for_creation/Wikipedia_for_dummies

also - Wikipedia_talk:Articles_for_creation/testing_scripts_with_proveit_-_text_page#Test_page_to_show_problems_with_Proveit_tool_not_working_under_Wikipedia_talk:Articles_for_creation. Optionally, what is your Wikipedia username?  If you do not wish to post it here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ).  This will help us see any potentially conflicting scripts. User:Media-hound-_thethird Please provide any additional information below. Annoying bug when you recommend proveit as a great tool to newbie editors, and then when they get their first article declined the most obvious place to work and resolve issues is blocked. Proveit just vanishes. Other tools/scripts work fine.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=144_

**Comment by lfschenone** [comment]
WONTFIX, see https://github.com/proveit-js/proveit/issues/176
