### ISSUE TITLE
Auto-detect date format from category

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#142]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on June 25, 2012 20:15:50_

For articles in Category:Use_dmy_dates or Category:Use mdy dates (or sub-categories thereof), use the appropriate date format.

Once the localization is done, this should override the date localization.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=145_

**Comment by Sophivorus** [comment]
See #231
