### ISSUE TITLE
Link to correct user page on non-english wikis

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#143]
_From [Eckankar](https://code.google.com/u/Eckankar/) on July 21, 2012 12:20:10_

What steps will reproduce the problem? Make an edit on a non-English WP using ProveIt. What is the expected output? What do you see instead? The edit message will contain "(edited with [[User:ProveIt_GT|ProveIt]])".
The edit message should contain "(edited with [[en:User:ProveIt_GT|ProveIt]])", since the other link doesn't work on wikis other than en. When were you using ProveIt? On what browser (including version) and operating system? Chrome dev, Windows. Optionally, what is your Wikipedia username?  If you do not wish to post it here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ).  This will help us see any potentially conflicting scripts. Sebbe on en. and da.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=146_

**Comment by sophivorus** [comment]
This was fixed many commits ago.
