### ISSUE TITLE
Can't edit an existing ref, ever

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#144]
_From [vimaleshvara](https://code.google.com/u/112262251653094255251/) on August 07, 2012 00:50:10_

What steps will reproduce the problem? 1.attempting to edit an existing ref
2.allows data entry
3.results don't appear on the page

What is the expected output? 
changes
What do you see instead?
no change

When were you using ProveIt?
since 1 year or so

 On what browser (including version) and operating system? Win 7, Firefox up to 14 If page-specific, what article were you editing? Optionally, what is your Wikipedia username?
DadaNeem
  If you do not wish to post it here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ).  This will help us see any potentially conflicting scripts. Please provide any additional information below.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=147_

**Comment by sophivorus** [comment]
This report refers to the previous version of the gadget. The new version is too different for this report to still be relevant.
