### ISSUE TITLE
a new <ref> name doesn't appear on wiki page, ever

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#145]
_From [vimaleshvara](https://code.google.com/u/112262251653094255251/) on August 07, 2012 00:55:16_

What steps will reproduce the problem?
1. Data entry for a new ref including <ref> name
2. Insert into form

What is the expected output?
That <ref> name appears in form.

What do you see instead?
all data except <ref> name appear in form.

When were you using ProveIt?
For 1 year past

On what browser (including version) and operating system?
Firefox up to 14, Win 7

If page-specific, what article were you editing? Optionally, what is your Wikipedia username?  If you do not wish to post it here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ). This will help us see any potentially conflicting scripts. Please provide any additional information below.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=148_

**Comment by sophivorus** [comment]
This issue refers to the previous version. The new version is too different for this report to be still relevant.
