### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#146]
_From [silentlamb67](https://code.google.com/u/117022365762290141223/) on October 03, 2012 18:58:53_

en.Wikipedia User:Green Cardamom
System: Windows 7 64-bit, Firefox 15.01

I enabled it through en.wikipedia Preferences and can see the bar in the lower right corner but it reports 0 references for any article, and when click on "Add References" nothing happens, the window doesn't pop up. Nothing happens when highlighting a reference. I can, however, run OK the demo on your website where it works fine so believe my browser is working properly. I don't know what else to do. Thank you. If you can contact my Wikipedia account. 
Green Cardamom

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=149_

**Comment by sophivorus** [comment]
The latest version works.
