### ISSUE TITLE
Support cite pmid

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#147]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on November 15, 2012 17:30:41_

Support the cite pmid reference type.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=150_

**Comment by sophivorus** [comment]
The Template:Cite pmid is deprecated and so support for it is no longer desirable nor needed.
