### ISSUE TITLE
Support HTTPS (TLS/SSL) for ProveIt web site

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#149]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 06, 2012 20:53:04_

Support HTTPS (TLS) for the ProveIt web site.  This will be after it is up and running on labs (issue #151).  HTTP should continue to work, or forward to HTTPS (preserving path and query string).

This includes changing the link in ProveIt itself to be protocol-relative.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=152_

**Comment by Sophivorus** [comment]
Website will probably be phased out, see #205
