### ISSUE TITLE
Add proveit- prefix for namespacing

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#151]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 08, 2012 22:28:27_

Add proveit- prefix to all IDs and classes to avoid possible namespace issues.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=154_

**Comment by lfschenone** [comment]
Done in the latest version.

**Comment by mattflaschen** [comment]
No, there are still some that use unprefixed and need to be fixed.

**Comment by sophivorus** [comment]
Now yes, I've added the 'proveit' prefix to the remaining classes and ids.
