### ISSUE TITLE
Enter/return should save a reference

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#152]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 09, 2012 04:30:42_

Pressing enter or return should add or save the reference.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=155_

**Comment by Sophivorus** [comment]
Done in the latest version, deployed in the Spanish Wikipedia and will soon be deployed in the English Wikipedia.
