### ISSUE TITLE
Consider using autoEllipsis module

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#153]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 09, 2012 18:36:55_

Consider using jquery.autoEllipsis instead of our truncateTitle.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=156_

**Comment by Sophivorus** [comment]
The current version has another approach: the data shown in the reference list is that of the required parameters, in full. If the data spans more than one line, then the item spans more than one line, and this doesn't look ugly nor does it become a usability problem.
