### ISSUE TITLE
Upgrade yuidoc

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#154]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 09, 2012 22:40:25_

It apparently was rewritten to use node.js and JavaScript.  The current version we're using is quite old.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=157_

**Comment by sophivorus** [comment]
I tried updating the yuidocs and it worked, but the documentation was empty because the comments don't have the proper syntax. However, I think that the gadget is way too small to benefit from this kind of documentation, it's just a single file!
