### ISSUE TITLE
Add support for cite quick

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#155]
_From [krinklemail](https://code.google.com/u/113562984096592077629/) on December 13, 2012 00:03:37_

What steps will reproduce the problem? 1. Visit https://en.wikipedia.org/w/index.php?title=Barack_Obama&action=edit&editintro=Template:BLP_editintro 2. Find <ref name="maraniss">
3. Edit it

Expected result:
field "Author"

Actual result:
field "news|author"

Wikitext source:

<ref name="maraniss">{{cite quick |news|date=August 24, 20080|author=Maraniss, David|title=Though Obama had to leave to find himself, it is Hawaii that made his rise possible|newspaper=The Washington Post|page=A22|url= http://www.washingtonpost.com/wp-dyn/content/article/2008/08/23/AR2008082301620.html|accessdate=October 28, 2008}}</ref>

Additional information:

When I rearranged the parameters it turns out that it always the one right after "news|" for which the label is broken, presumably due to a the parameter parser not covering for the concept of numbered parameters, looking only for "|=" instead of "|" (optionally with =), thus sees "news|author" as the key instead of "author".

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=158_

**Comment by sophivorus** [comment]
The Template:Cite quick was deleted, support is no longer needed.
