### ISSUE TITLE
Change reference objects to use prototypal inheritance

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#156]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on February 04, 2013 23:32:30_

Change reference objects to use standard JavaScript prototypal inheritance.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=159_

**Comment by lfschenone** [comment]
Done in the latest version. :-)
TemplateReference inherits from RawReference which in turn inherits from Citation.

**Comment by mattflaschen** [comment]
It's using the same style as before.

I want to use methods attached to the prototype, rather than every object.

It currently uses this style (attaching to each object), which I want to switch away from:

```
this.getIcon = function () {
```

**Comment by mattflaschen** [comment]
We should use OOjs for this (not OOjs UI yet, though).

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148219
