### ISSUE TITLE
Extract out using into wrapper script

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#157]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 01, 2013 02:26:20_

Using the wrapper dev script as described at #153, the using call should also be pulled into the wrapper.  That keeps the main script smaller (and slightly faster) and still allows successful dev usings to be copied (modulo formatting) into the gadget definition.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=160_

**Comment by sophivorus** [comment]
I don't understand this issue. Could you explain it in less technical terms?

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148221
