### ISSUE TITLE
Add archiveurl and archivedate as default parameters

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#158]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 01, 2013 03:44:24_

Add archiveurl and archivedate for all types where url is default and the archive ones are supported.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=161_

**Comment by lfschenone** [comment]
Done in the latest version.
