### ISSUE TITLE
Add jstor parameter to cite journal

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#159]
_From [ylee@pobox.com](https://code.google.com/u/109751298859365029458/) on March 02, 2013 00:51:00_

Adding a "jstor" field to Journal mode would be very helpful, as JSTOR citations do not include DOI data.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=162_

**Comment by lfschenone** [comment]
Done.
