### ISSUE TITLE
Consider moving static images to Wikimedia Commons

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#160]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 11, 2013 00:05:09_

I noticed an issue where ProveIt sometimes failed to fully load, and so got stuck in the upper left.  Ori Livneh reported this was due to intermittent 500 errors.

If this remains an issue, consider moving them to Wikimedia Commons.  Unlike Google Code, Commons is designed to host images, and should be more reliable.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=163_

**Comment by lfschenone** [comment]
Currently, all icons are served from Commons. Is this what this issue is about? Is is still an issue?

**Comment by mattflaschen** [comment]
Yeah, I forgot this was a (filed) issue.  It was fixed and tagged as part of the larger #173.
