### ISSUE TITLE
Preserve spacing on edit

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#161]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 20, 2013 16:54:23_

When editing, preserve the spacing style, at least for unchanged fields.

See https://en.wikipedia.org/w/index.php?title=User_talk:ProveIt_GT&oldid=545777967#Please_don.27t_unnecessarily_rewrite_references_in_your_favorite_style.. .

If ProveIt hooks into the VisualEditor API, they may make this easier.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=164_

**Comment by lfschenone** [comment]
This feature seems very hard to implement, and for some (like me) spacing normalisation is a feature, not a bug. Also, most wikipedians prefer the current enforced spacing style. I think we should vote here. I vote for keeping the current spacing normalisation feature.

**Comment by Sophivorus** [comment]
Thinking again, there is one sensible way to implement this. TemplateData allows to mark the preferred layout of a template as either "inline", "block" or "unspecified". ProveIt could normalize the layout of the template according to the preferred layout for it, or if no layout is specified, guess the current layout by checking how many line breaks there are.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148222
