### ISSUE TITLE
Implement labelling for arbitrary number of authors and editors

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#162]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on April 08, 2013 18:54:04_

The CS1 templates now support an arbitrary number of authors (not just first9, last9, author9, etc.) and editors.

This was reported by Gadget850.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=165_

**Comment by sophivorus** [comment]
The parameters available now depend on TemplateData, so adding support for arbitrary number of authors is no longer desirable. The current TemplateData for the Template:Cite book allows for up to 9 authors and editors, which is enough for 99,999% of the references out there.
