### ISSUE TITLE
IUCN support

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#164]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on April 25, 2013 15:14:32_

FrigidNinja requested support for https://en.wikipedia.org/wiki/Template:IUCN , which is often used with <ref>, e.g. in infoboxes like https://en.wikipedia.org/w/index.php?title=Carolina_Parakeet&action=edit

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=167_

**Comment by sophivorus** [comment]
This can be fulfilled as soon as someone adds <templatedata> to the documentation.
