### ISSUE TITLE
Does not update edit form

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#165]
_From [pss0331@hotmail.com](https://code.google.com/u/109680341388310118982/) on May 09, 2013 17:54:10_

What steps will reproduce the problem? I was adding an author, newspaper, and date to a {{cite news}} source on the "Area codes 281, 346, 713, and 832" article. However, it has happened before with different sources. What is the expected output? What do you see instead? The expected output was that this information was added. However, it was not. When were you using ProveIt? On what browser (including version) and operating system? Yes. I was using Firefox 20.0.1 on Windows 7 Home Premium SP1 (64-bit). If page-specific, what article were you editing? No. Optionally, what is your Wikipedia username?  If you do not wish to post it here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ).  This will help us see any potentially conflicting scripts. Presidentman Please provide any additional information below. No additional comment.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=168_

**Comment by lfschenone** [comment]
This seems to be an issue of a previous version. No such problem with the latest.
