### ISSUE TITLE
wikEd incompatibility (w/workaround) - 'cite a reference' fails -- "insert this reference at cursor" doesn't.

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#167]
_From [elvey.matthew](https://code.google.com/u/101773370638574520025/) on June 07, 2013 19:25:53_

What steps will reproduce the problem? Select a (Cite-formatted) reference in ProveIt using the instructions provided. (works)
Click in the Wikipedia edit form where you want the new citation to appear. (works too)
Click the "insert this reference at cursor" button beneath the selected reference info in ProveIt. 

What is the expected output? 
This will insert the abbreviated reference text into the Wikipedia edit form where you left your cursor. 

What do you see instead?
Nothing is inserted.  The window flashes and briefly scrolls up to the top of the page, and then down to partially display the edit field. When were you using ProveIt? On what browser (including version) and operating system? Now.  Firefox on OSX, both updated to the latest production versions : 21.0 and 10.8.4. If page-specific, what article were you editing? I think it isn't, but FYI, this is the edit I did: http://en.wikipedia.org/w/index.php?title=Public_domain&diff=next&oldid=558813986 Optionally, what is your Wikipedia username? See edit link. I do have custom scripts. Please provide any additional information below. This may be related to issue 168 , which also mentions wikEd.
My workaround may help with it and/or issue 118 / issue 120 WORKAROUND:
If I disable wikEd, by clicking the "Toggle between classic text area and wikEd" button, ProveIt works fine. Then I can click the toggle button again and use wikEd as usual...

(P.S. A release notes page with mention of known bugs would be helpful.  A link on http://proveit.wmflabs.org/users/bugreport to http://code.google.com/p/proveit-js/issues/list would be about as helpful, and easier.)

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=170_

**Comment by Sophivorus** [comment]
This was an issue with the old version. No longer applies as the code changed radically, and also the "Insert reference at cursor" function is currently removed, though it will return soon, see #232
