### ISSUE TITLE
Tool shows up behind wikipedia globe

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#168]
_From [gethemudo](https://code.google.com/u/118269474389403837310/) on June 22, 2013 06:34:21_

1. Use the proveit-js in portuguese wikipedia
2. Click the edit button on any article

The tool should show up on top of the edit window, instead it appears behind the Wikipedia logo on the top left corner of the screen.

On Firefox 21.0, on Mac OSX 10.6.8

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=171_

**Comment by lfschenone** [comment]
The latest version surely doesn't have this bug. Also the Portuguese Wikipedia doesn't have ProveIt enabled.
