### ISSUE TITLE
Use TemplateData for parameter information

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#169]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on June 29, 2013 18:52:14_

It is possible to use the TemplateData API ( https://www.mediawiki.org/wiki/Extension:TemplateData#Using_the_TemplateData_API ), even in wikitext mode.  This could at first be as a fallback for unknown parameters.  That would allow supporting new parameters and eventually just removing the hard-coded template definitions in ProveIt.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=172_

**Comment by lfschenone** [comment]
I think this is issue is key. It would save us a lot of maintenance work and make the gadget immediately useful and updated in all Wikipedias.

**Comment by mattflaschen** [comment]
Yes, agreed.

We should also try to cache the TemplateData for a reasonable time period in localStorage (to avoid network requests) (or another local cache).  VE may already have code for this.  If not, caching it shouldn't be that complicated (localStorage sometimes fills up, but we'll just use a direct API call if it's missing in cache).

This also means if people want to improve support for ProveIt, they'll improve everything that uses TemplateData.

**Comment by sophivorus** [comment]
Done! :-)
Cache is still missing, but the current implementation does a single request to get all the templates data and it stores until the user refreshes or changes the page, so it isn't too inefficient.
