### ISSUE TITLE
Right-side add/edit buttons misplaced in MacOS Firefox

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#17]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on August 09, 2010 11:35:00_

In the MacOS version of Firefox, the cancel and save buttons (for add and edit tabs) aren't in line with the add field button, which is positioned correctly. Instead, for some reason, they are ~10 pixels too low. This is probably a CSS issue.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=17_

**Comment by lfschenone** [comment]
Fixed in the latest version.
