### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#170]
_From [ebraminio](https://code.google.com/u/ebraminio/) on September 09, 2013 16:01:12_

This translation is done by User:Reza1615 here https://fa.wikipedia.org/w/index.php?title=&#37;D8&#37;A8&#37;D8&#37;AD&#37;D8&#37;AB_&#37;D9&#37;85&#37;D8&#37;AF&#37;DB&#37;8C&#37;D8&#37;A7&#37;D9&#37;88&#37;DB&#37;8C&#37;DA&#37;A9&#37;DB&#37;8C:Gadget-ProveIt2.js&oldid=10878121 fa :
		{
			agency: "سازمان",
			name: "نام",
			author: "نویسنده (نام خانوادگی، نام)",
			author2: "نویسنده ۲ (نام خانوادگی، نام)",
			author3: "نویسنده ۳ (نام خانوادگی، نام)",
			author4: "نویسنده ۴ (نام خانوادگی، نام)",
			author5: "نویسنده ۵ (نام خانوادگی، نام)",
			author6: "نویسنده ۶ (نام خانوادگی، نام)",
			author7: "نویسنده ۷ (نام خانوادگی، نام)",
			author8: "نویسنده ۸ (نام خانوادگی، نام)",
			author9: "نویسنده ۹ (نام خانوادگی، نام)",
			last: "نام خانوادگی",
			last2: "نام خانوادگی (نویسنده ۲)",
			last3: "نام خانوادگی (نویسنده ۳)",
			last4: "نام خانوادگی (نویسنده ۴)",
			last5: "نام خانوادگی (نویسنده ۵)",
			last6: "نام خانوادگی (نویسنده ۶)",
			last7: "نام خانوادگی (نویسنده ۷)",
			last8: "نام خانوادگی (نویسنده ۸)",
			last9: "نام خانوادگی (نویسنده ۹)",
			first: "نام",
			first2: "نام (نویسنده ۲)",
			first3: "نام (نویسنده ۳)",
			first4: "نام (نویسنده ۴)",
			first5: "نام (نویسنده ۵)",
			first6: "نام (نویسنده ۶)",
			first7: "نام (نویسنده ۷)",
			first8: "نام (نویسنده ۸)",
			first9: "نام (نویسنده ۹)",
			authorlink: "نام مقاله نویسنده",
			title: "عنوان",
			trans_title: "عنوان به انگلیسی",
			publisher: "ناشر",
			year: "سال",
			location: "مکان",
			place: "محل اثر",
			isbn: "ISBN",
			id: "شناسه",
			doi: "DOI",
			page: "صفحه",
			pages: "صفحات",
			quote: "نقل قول",
			month: "ماه",
			journal: "ژورنال",
			edition: "ویرایش",
			volume: "جلد",
			issue: "موضوع",
			url: "نشانی اینترنتی",
			date: "تاریخ نشر",
			accessdate: "تاریخ دسترسی",
			coauthors: "نویسنده همکار",
			booktitle: "عنوان صورت جلسه",
			contribution: "همکاری/فصل",
			encyclopedia: "دانشنامه",
			newsgroup: "گروه خبری",
			version: "نسخه",
			site: "وب‌گاه",
			newspaper: "روزنامه",
			"publication-place": "محل نشر",
			editor: "ویرایستار (نام خانوادگی، نام)",
			article: "مقاله",
			pubplace: "محل ناشر",
			pubyear: "سال نشر",
			inventor: "مخترع (نام خانوادگی، نام)",
			"issue-date": "تاریخ",
			"patent-number": "شماره اختراع",
			"country-code": "کد کشور (XX)",
			work: "اثر",
			format: "ساختار",
			issn: "ISSN",
			pmid: "PMID",
			chapter: "فصل",
			web: "وب",
			book: "کتاب",
			conference: "کنفرانس",
			news: "اخبار",
			paper: "مقاله",
			"press release": "خبرگزاری",
			interview: "مصاحبه",
			"AV media": "اثر سمعی",
			subject: "موضوع",
			subjectlink: "عنوان مقاله",
			subject2: "عنوان ۲",
			subjectlink2: "عنوان ۲ مقاله",
			subject3: "عنوان ۳",
			subjectlink3: "عنوان ۳ مقاله",
			subject4: "عنوان ۴",
			interviewer: "مصاحبه‌گر",
			cointerviewers: "عمکار مصاحبه‌گران",
			type: "نوع",
			program: "برنامه",
			callsign: "نشانی تماس",
			city: "شهر",
			archiveurl: "نشانی اینترنتی بایگانی",
			archivedate: "تاریخ بایگانی",
			episode: "اپیزود",
			episodelink: "عنوان مقاله اپیزود",
			series: "سریال",
			serieslink: "عنوان مقاله سریال",
			credits: "اعتبار",
			network: "شبکه",
			station: "ایستگاه",
			airdate: "تاریخ پخش",
			began: "تاریخ شروع",
			ended: "تاریخ اتمام",
			season: "شماره فصل",
			seriesno: "شماره فصل",
			number: "شماره",
			minutes: "دقیقه",
			transcript: "رونوشت",
			transcripturl: "نشانی اینترنتی رونوشت",
			people: "افراد",
			medium: "رسانه تولیدی",
			language: "زبان",
			time: "زمان",
			oclc: "OCLC",
			ref: "Anchor ID",
			deadurl: 'نشانی اینترنتی مرده؟',
			raw: 'ساختار ناشناخته'
		},
Please apply it. Thank you

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=173_

**Comment by sophivorus** [comment]
With the new TemplateData, adding support for Persian is just a matter of translating the few interface messages, and adding the list of templates that use TemplateData.

**Comment by Sophivorus** [comment]
This localization is now obsolete.
