### ISSUE TITLE
Add CSS classes for testability

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#171]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on October 13, 2013 21:03:50_

In addition to issue 154 , having clear classes (e.g. proveit-small-icon-edit for the pencil icon in the unexpanded references view) will ease Cucumber browser testing.

See https://gerrit.wikimedia.org/r/#/c/87436/

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=174_

**Comment by lfschenone** [comment]
CSS has now clear classes, but testability is still an issue.
