### ISSUE TITLE
Move yuidoc to use rsync

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#172]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on October 30, 2013 22:31:24_

Remove the old ssh-walking code, change the yuidoc to use rsync, and get it working again.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=175_

**Comment by sophivorus** [comment]
I removed the yuidocs. When I found them they were broken and outdated. I updated them to document the latest code, but they didn't parse the comments correctly. The comments would need to be rewritten for the latest yuidocs to be generated correctly. However, the gadget is quite small (a single file, come on) so yuidocs don't seem necessary or useful.
