### ISSUE TITLE
Use responsive design for small screen sizes

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#174]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on November 08, 2013 21:18:50_

ProveIt could act as a full screen interface on small screens.  One idea is to have only the P logo in the bottom right (minimized view), then when that's clicked/touched, maximize to the full screen to allow adding or editing a reference.  The gadget will need to run on mobile, if it's not already.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=177_

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148224
