### ISSUE TITLE
Internationalization and localization to Spanish

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#175]
_From [schenonef](https://code.google.com/u/110725075904602808447/) on December 18, 2013 08:31:19_

Hi all,
I'm starting an effort to fully internationalize the ProveIt extension, and also to localize it to Spanish (my native language). For this end I've created two clones: https://code.google.com/r/schenonef-proveit-i18n/ https://code.google.com/r/schenonef-proveit-spanish/ I'll work first on the internationalization, then on the localization. The general plan for the internationalization is to move all the hard-coded text to the descriptions array, and also add to the array the citation templates names and their parameters. In the Spanish Wikipedia, the citation templates are not called "Cite book", "Cite news", etc., but "Cita libro", "Cita noticias", etc., and the parameters are not called "author", "title", etc., but "autor", "título", etc. Thus the gadget should insert, in the Spanish Wikipedia, things like {{cita libro |autor= |título=}}, instead of {{cite book |author= |title=}} To accomplish this, my idea is to move all the template names and parameter names to the descriptions array.

Some Wikipedias may also have some completely different parameters from the English ones, and even some completely different templates, so I'll try to give the gadget enough flexibility to accommodate these differences.

Once all of this is done, I'll move on to localizing the gadget to Spanish.

Mathew, Kurt, Neoyaku, please keep an eye on the clones, and if you support the changes, please consider merging them into the main repo, or even giving me commit access to speed up the process.

Kind regards,
Felipe

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=178_

**Comment by lfschenone** [comment]
Done.
