### ISSUE TITLE
Support AFC psuedo-namespace and Draft namespace

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#176]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on January 04, 2014 16:10:36_

Show ProveIt in the AFC psuedo-namespace (Wikipedia talk:Articles for creation) and the Draft namespace.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=179_

**Comment by lfschenone** [comment]
Draft namespace is supported now.
I checked the AFC project and it seems that all current submissions are being created under the Draft namespace. So it looks like we don't need to support the AFC pseudo-namespace any more.
