### ISSUE TITLE
Proveit does not show up in hindi language wiki

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#177]
_From [shubhamsizzles](https://code.google.com/u/107236294438039854289/) on January 26, 2014 08:29:17_

What steps will reproduce the problem? 1. Added 

mw.loader.load( ' http://en.wikipedia.org/w/index.php?title=User:ProveIt_GT/ProveIt.js&action=raw&ctype=text/javascript' );
// [[:en:User:ProveIt GT]]

to both my common.js and vector.js pages
2. Purged cache
3. Reloaded article page and clicked स्रोत सम्पादित करें (equivalent to edit tab)

The proveit box does not appear on the bottom right corner When were you using ProveIt? On what browser (including version) and operating system? Google Chrome 32 
Windows 8 64 bit If page-specific, what article were you editing? Not page specific Optionally, what is your Wikipedia username?  If you do not wish to post it Shubhamkanodia here, you can privately email the team ( http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT ).  This will help us see any potentially conflicting scripts. Please provide any additional information below.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=180_

**Comment by lfschenone** [comment]
The latest version works fine in all wikis, see my common.js and common.css for the proper way to do it:
https://hi.wikipedia.org/wiki/User:Luis_Felipe_Schenone/common.js
https://hi.wikipedia.org/wiki/User:Luis_Felipe_Schenone/common.css
