### ISSUE TITLE
Add jshint to enforce coding conventions

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#180]
Update code to use the MediaWiki coding conventions ([JavaScript](https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript), [CSS](https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS)).  @lfschenone did this in his branch, so we're both familiar with the conventions.

**Comment by lfschenone** [comment]
The latest version complies with the MediaWiki coding conventions. There may be a detail here or there, but 99% complies. We should still add a jshint though.

**Comment by Sophivorus** [comment]
@mattflaschen I'm not sure how to accomplish this. I added a .jshintrc file to the repo, but now what??

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148225
