### ISSUE TITLE
cite patent template addition

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#181]
_From [unrealze](https://code.google.com/u/113479348363973543646/) on March 02, 2014 11:00:47_

Hello. This is not a bug report, but a simple request. Perhaps you could add "Template:Cite patent" into the list of possible citations? Thanks.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=181_

**Comment by lfschenone** [comment]
The latest version includes the Template:Cite patent
