### ISSUE TITLE
Truncating number of references

### ISSUE THREAD

**Issue by DRanged1** [proveit-js/proveit#184]
What steps will reproduce the problem?

1.Open https://en.wikipedia.org/w/index.php?title=Virginia_Tech_massacre
2.Launch ProveIt
3.Note the References count on the left

What is the expected output?
192
What do you see instead?
187
When were you using ProveIt?
May 3, 2014
On what browser (including version) and operating system?
Google Chrome Version 34.0.1847.131 m; Windows 7 Home Premium Service Pack 1 (64-bit)
If page-specific, what article were you editing?
Virginia Tech massacre
Optionally, what is your Wikipedia username?  If you do not wish to post ithere, you can privately email the team (http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT).  This will help us see any potentially conflicting scripts.
D'Ranged 1
Please provide any additional information below.

**Comment by lfschenone** [comment]
I checked the article in the report date with the latest version of ProveIt and the count is correct. However, it isn't correct with the old version of ProveIt (the one still in use in the English Wikipedia). Therefore, the latest version already solves this issue.
