### ISSUE TITLE
Check for deprecated parameters

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#186]
There is a report of deprecated parameters given at https://en.wikipedia.org/w/index.php?title=User_talk:ProveIt_GT&oldid=612730423#Deprecated_parameters .

They should be removed, since they will stop working soon.  Already, they put pages in a fixup category.

**Comment by lfschenone** [comment]
The latest version doesn't include the deprecated parameters. However, the English Wikipedia still has the pre-i18n version running. Should we try to update already? Or is there some big bug or something missing?

**Comment by mattflaschen** [comment]
No, I just need to test and deploy it.  I expect to get to it soon.
