### ISSUE TITLE
Add Citoid support

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#199]
[Citoid](https://www.mediawiki.org/wiki/Citoid) is a service that allows generating a citation from a URL.

**Comment by sophivorus** [comment]
See https://en.wikipedia.org/wiki/User:Zhaofeng_Li/reFill

**Comment by mattflaschen** [comment]
I'm interested in working on this, so I'm tentatively assigning this to myself.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148226
