### ISSUE TITLE
{{Open access}} is stripped out

### ISSUE THREAD

**Issue by mackensen** [proveit-js/proveit#202]
To reproduce:

1. Edit an article with a reference which includes the `{{Open access}}` template
2. Make a change to the reference
3. Save (or preview)

Since `{{Open access}}` is outside the citation template the expectation is that nothing will change, but the rewritten citation removes the template, leaving `<ref>{{cite whatever}}</ref>` only. This means among other issues you can't use ProveIT with standard newspapers.com references.

**Comment by sophivorus** [comment]
More generally, we should modify ProveIt so that editing a template only modifies the template code, and leaves everything outside of it untouched.

**Comment by Sophivorus** [comment]
Or maybe all text before the template should be shown in its own field, and all text after the template in its own field too.

**Comment by Sophivorus** [comment]
Fixed in the latest!
