### ISSUE TITLE
ProveIt failure in zh-wikipedia

### ISSUE THREAD

**Issue by wck8888wck** [proveit-js/proveit#206]
What steps will reproduce the problem?

1.try to edit a page as usual (in main namespace)
2. 
3.

What is the expected output?
It should like enwiki, where proveit will provide spaces for you to fill in everything
What do you see instead?
Only {{cite book}} is still working, others options show nothing. If you still insert it (without filling anything because you can't), it shows {{cite undefined}}
When were you using ProveIt?
normally
On what browser (including version) and operating system?
Firefox 35.01 ,win 7 Taiwan version
If page-specific, what article were you editing?

Optionally, what is your Wikipedia username?  If you do not wish to post ithere, you can privately email the team (http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT).  This will help us see any potentially conflicting scripts.
:zh:user:Temp3600
Please provide any additional information below.

**Comment by wck8888wck** [comment]
{{cite episode}} and {{cite AV media}} are still working too

**Comment by lfschenone** [comment]
Just tested the latest version in zhwiki, no problems.
