### ISSUE TITLE
Auto-generated ref names

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#21]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on August 11, 2010 17:35:50_

We had discussed the possibility of auto-generating reference names (e.g. <ref name="">) for references that lack them.

Benefits:

- Potentially hide all UI elements dealing with ref names. Ref names are one of the most confusing aspects of refs on Wikipedia and removing those elements could avoid a lot of confusion.

- Enable ibid. button for every ref. If the ref lacks a name, ProveIt auto-generates one behind the scenes.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=21_

**Comment by lfschenone** [comment]
Doesn't seem like a good idea to me. I think that the current UI is relatively clear regarding ref names. Adding ref names to everything would clutter the wikitext, and users would justly complain of unintended edits (I know I wouldn't like it).

**Comment by mattflaschen** [comment]
I actually still think this is worth considering.  VE does auto-generate them as needed, for similar reasons.

ProveIt also wouldn't do it for everything, only as needed (when you create a new citation/pointer to a reference without a ref name).

I think we should probably still allow the user the *option* to specify a ref name, for readability.

**Comment by Sophivorus** [comment]
The latest version now allows to insert citations to references without name, by prompting the user to input a name. Still not sure if we should auto-generate behind the scenes.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148210
