### ISSUE TITLE
Proveit fails in ta.wiki

### ISSUE THREAD

**Issue by AntanO** [proveit-js/proveit#211]
Many user reported that ProveIt does not work or disappear in Tamil Wikipedia. It happened recently (2 - 3 days). I too experience that I could not see ProveIt. It looks like when we disable ProveIt "preferences page".

I use it more than two years. My browser is Google Chrome and version is 44.0.2403.130 m. OS is Windows 7

My user name is AntanO. I tried to get this feature by AntanO/common.js but fails

In addition, I have experienced previously that ProveIt was not minimize when add references. It was stays like "always on top" feature.

**Comment by lfschenone** [comment]
Just tested the latest version it tawiki, no problems.
