### ISSUE TITLE
ProveIt blocks bottom of wikEd edit window on English Wikipedia

### ISSUE THREAD

**Issue by Checkingfax** [proveit-js/proveit#218]
What steps will reproduce the problem?

1. Open any page in edit-source on en-Wikipedia with wikEd enabled
2. Scroll to bottom of page
3. ProveIt will block part of the edit buttons.

What is the expected output?
ProveIt needs to auto-hide more completely. There is no need for a one inch band of it to stay visible while it is waiting to be launched.

When were you using ProveIt?
Today on English Wikipedia

On what browser (including version) and operating system?
Firefox v 44.0.2
Windows 7 Professional 64-bit

If page-specific, what article were you editing?
Any article or talk page, etc. when in edit-source view using wikEd text editor.

Optionally, what is your Wikipedia username?  If you do not wish to post it here, you can privately email the team (http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT).  This will help us see any potentially conflicting scripts.
Checkingfax

Please provide any additional information below.
I used to like ProveIt but am now seriously considering removing it because it is always in the way of the edit buttons and the very bottom two or three rows of text that I am trying to edit. This is especially problematic when doing a find/replace task.

Email me back when there is progress on this.

![proveit blocks my edit window](https://cloud.githubusercontent.com/assets/17428721/13250407/a18cdb4c-d9de-11e5-8f1e-7af06cf6baf6.png)

**Comment by Sophivorus** [comment]
@Checkingfax This should no longer be an issue. Not convinced that it ever was, as your screenshot clearly shows that you can scroll the page much more. Also, by clicking the [P] button you can hide ProveIt completely. I'm closing this issue, if you still experience this problem, please give me more precise instructions on how to reproduce it. Thanks!

![screen shot 2016-08-09 at 2 51 56 pm](https://cloud.githubusercontent.com/assets/3542266/17527225/db8e2c24-5e40-11e6-8137-6d2c1f10a9f6.png)
