### ISSUE TITLE
Migrate to Gerrit

### ISSUE THREAD

**Issue by Sophivorus** [proveit-js/proveit#221]
I remember that when migrating from code.google.com to GitHub this option was considered and I voted we should migrate to GitHub rather than Gerrit. However, back then I didn't know that every repo at Gerrit gets a GitHub mirror under github.com/wikimedia Therefore, every repo at Gerrit gets all the advantages of being at Gerrit, plus all the advantages of being at GitHub.

The current gadget landscape is a mighty mess, with different versions of different gadgets distributed through hundreds of wikis. The community could benefit greatly from a centralised repository of gadgets, and the most natural solution to that would be to host them at Gerrit + GitHub mirrors

If we migrate to Gerrit, ProveIt would become the first gadget to do so, and would set the example for others to follow.

By being at Gerrit, the gadget would win an extra level of trust that may soon translate (I believe) in a bot or some other mechanism that will automatically update the code at Commons (see issue #219) with any updates pushed to Gerrit.

The repo at Gerrit has already been created, see https://gerrit.wikimedia.org/r/wikipedia/gadgets/ProveIt
And the GitHub mirror already exists, see https://github.com/wikimedia/wikipedia-gadgets-ProveIt
Should we migrate then? Or should I request them be deleted?

**Comment by Sophivorus** [comment]
@mattflaschen Hi Matt! The repo is already created, and I was in the process of merging the two, when I encountered an error. In order to do the merge while preserving the HISTORY of the repo, I need you to register an account at Gerrit (https://gerrit.wikimedia.org) with the same email you use here at GitHub, so that Git knows to whom to assign your commits. Would you mind doing so? I think this will work, but because I've never done it before I can't be sure until I try. In case you're interested, the commands I'm using, following my research online, are the following:

```
# Clone the GitHub repo
git clone https://github.com/proveit-js/proveit.git

# Add the Gerrit repo as a new remote origin called “gerrit”
git remote add gerrit https://gerrit.wikimedia.org/r/wikipedia/gadgets/ProveIt.git

# Pull .gitreview from Gerrit
git pull --all gerrit

# Push everything to Gerrit
# This step is currently failing due to your email not being registered at Gerrit
git push --all gerrit

# Remove the GitHub remote
git remote rm origin

# Rename the Gerrit remote into just “origin”
git remote rename gerrit origin
```

Needless to say, when the repo is ready I'll give you full access. After this happens, and after I migrate all the issues from here to Gerrit, what will happen to this GitHub repo? Cheers!

**Comment by mattflaschen** [comment]
I'll close this GitHub once all the history and issues are moved over.

You should try requesting at https://www.mediawiki.org/wiki/Git/New_repositories/Requests .  It looks like they can import from GitHub (there is even a GitHub import there right now).  There are special rights that are relevant to this.  Mention that you want to preserve history and ask that they delete the current Gerrit repo to re-create it (there is nothing there now except .gitreview).

That request should get attention, but if not you can ping Chad Horohoe on IRC (^demon or ostriches), and point them to the on-wiki request.

**Comment by Sophivorus** [comment]
Migration complete! New repo is at https://gerrit.wikimedia.org/r/p/wikipedia/gadgets/ProveIt

@mattflaschen you're the Project Owner
