### ISSUE TITLE
Month tag is gone from cite journal 

### ISSUE THREAD

**Issue by ke4roh** [proveit-js/proveit#224]
What steps will reproduce the problem?

1. Cite a journal

What is the expected output? 
no "month" tag

What do you see instead? 
a "month" tag

When were you using ProveIt? 
June 21, 2016

On what browser (including version) and operating system?
Chrome Fedora 23

If page-specific, what article were you editing?

Optionally, what is your Wikipedia username?  If you do not wish to post ithere, you can privately email the team (http://en.wikipedia.org/wiki/Special:EmailUser/User:ProveIt_GT).  This will help us see any potentially conflicting scripts.
ke4roh

Please provide any additional information below.
This came to my attention by a notice from https://en.wikipedia.org/wiki/User:ReferenceBot , but if I had been paying attention, I would have noticed the red in the reference immediately after saving.

**Comment by Sophivorus** [comment]
@ke4roh ProveIt has recently changed a lot. It now gets the template parameters directly from the TemplateData of template documentation, so if the month tag (by which I understand you mean the "month" parameter) doesn't exist in the template, ProveIt will not add it. Try out the new version!
