### ISSUE TITLE
Bad Template names

### ISSUE THREAD

**Issue by In1quity** [proveit-js/proveit#235]
If we have two templates, for example a normal Template:Cite web and a strange Template:Cite web:Strange name ([Книга](https://ru.wikipedia.org/wiki/Шаблон:Книга) and [Книга:Биологический энциклопедический словарь](https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0:%D0%91%D0%B8%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%8D%D0%BD%D1%86%D0%B8%D0%BA%D0%BB%D0%BE%D0%BF%D0%B5%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C)), then ProveIt will think that this template = Cite web. I think ProveIt must give us the full name of strange template in this situation - Cite web:Strange name. 

[Check it, try to find 'empty' Книга](https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BA%D0%BE%D0%BC%D1%8B%D0%B5?action=edit&withJS=%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:Iniquity/ProveIt.js)

**Comment by Sophivorus** [comment]
I've been able to reproduce the problem. It seems that with certain template names, the gadget fails to scan them correctly. Probably a regex issue, or maybe related to encryption.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148235
