### ISSUE TITLE
Unregistered parameters get deleted

### ISSUE THREAD

**Issue by Sophivorus** [proveit-js/proveit#239]
If a parameter isn't defined in the TemplateData of the template, it will be **deleted** when ProveIt updates the reference. This is meant to normalize parameters, but it may also imply lost information. Should ProveIt be more conservative here and keep unregistered parameters?

**Comment by In1quity** [comment]
Yes, but may be you can highlight them? And make them uneditable?

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148236
