### ISSUE TITLE
Remove field buttons don't have hover state

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#27]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on August 26, 2010 12:51:38_

The remove field buttons don't have a hover state, though the other buttons do. They also behave slightly differently in other ways, such as the button icon being slightly off-center. It seems something is slightly broken with these buttons and should be fixed.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=27_

**Comment by lfschenone** [comment]
The current version got rid of all the buttons for removing fields. They are unnecessary, just leave the field blank and ProveIt will remove it.
