### ISSUE TITLE
When leaving edit or add screen without saving, prompt to save

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#29]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on August 31, 2010 15:46:35_

When leaving edit or add screen without saving, consider prompting the user to save changes.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=29_

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148211
