### ISSUE TITLE
[Web] Marketing / Tutorial Video for Home Page

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#43]
_From [Neoyaku2](https://code.google.com/u/Neoyaku2@gmail.com/) on September 11, 2010 20:10:29_

Video explaining what ProveIt is and does. 
(Video will probably be hosted on Youtube).

Will need:
1)List of features to cover in :60 (or less)
2)Script and (rough) Storyboard
3)Video Screen Capture
4)Voice-Over (if needed, could use in-video Text Only with music)
5)Compiling of materials in video editing application

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=43_

**Comment by lfschenone** [comment]
I think this is highly unnecessary. Good documentation with images are enough, and they even have the advantage of being easier to update. I'd like to close this @mattflaschen, but what do you think?
