### ISSUE TITLE
Support editing name for RawReference

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#62]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on October 04, 2010 21:35:13_

It should be possible to edit the name of a RawReference.  This will enable inserting citations (pointers).

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=62_

**Comment by Sophivorus** [comment]
@mattflaschen Done!
