### ISSUE TITLE
Allow removing references and citations

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#71]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on October 21, 2010 17:23:03_

Provide GUIs for removing both references and citations.  If a reference is removed, all associated citations should be removed automatically (possibly with confirmation prompt).  The user should be able to remove citations individually through the GUI.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=71_

**Comment by lfschenone** [comment]
I'm not sure if this is worth it. Clicking on a reference highlights it, so we're already one backspace away from deleting it, and deleting references isn't such a common task that we should make it even easier. Not putting a delete button would force the user to give a second look and second thought to the reference before deleting it.

Regarding the case in which a reference with citations is deleted, I think that a confirmation prompt is a good approach, but I'm not sure of the exact way it would work. When a user hits the backspace, check for citations, and prompt for confirmation before continuing?

**Comment by Sophivorus** [comment]
The latest version now allows to remove references, and when doing so, all citations are removed too. Removing citations is a bit more manual, but still very practical: when clicking on a citation number in the ProveIt GUI, the citation is highlighted, so we're just one backspace away from deleting it.
