### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#73]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on October 26, 2010 15:28:37_

Needs content and formatting fixes.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=73_

**Comment by lfschenone** [comment]
I think we should create a documentation page at https://commons.wikimedia.org/wiki/Help:Gadget-ProveIt, to keep in line with https://commons.wikimedia.org/wiki/Help:Gadget-HotCat
Ok?

**Comment by Sophivorus** [comment]
Documentation page has been created at https://commons.wikimedia.org/wiki/Help:Gadget-ProveIt
