### ISSUE TITLE
Explore possibility of support for other MediaWiki instances, e.g. Wikia

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#77]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on October 28, 2010 13:31:22_

We should reexamine the possibility and technical barriers to making ProveIt usable beyond Wikipedia, e.g. Wikia or other MediaWiki instances.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=77_

**Comment by lfschenone** [comment]
Now that the template definitions have been abstracted from the core of the gadget, Wikia and other MediaWiki wikis should be able to use the gadget, if they just define their own templates.

**Comment by mattflaschen** [comment]
Yeah, I think they could do it pretty easily now by providing their own l10n file (which could be forked from the Language Wikipedia one if some of those templates are reused).
