### ISSUE TITLE
Policy tab

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#84]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on November 30, 2010 16:27:19_

ProveIt should have a Policy tab that shows up on article talk pages.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=84_

**Comment by lfschenone** [comment]
Why? Why talk pages? I don't understand!

**Comment by mattflaschen** [comment]
Yeah, I don't recall what this refers to (maybe something about verifiability policy, but I don't know).  (It might be useful to have ProveIt on talk pages to propose text with references for inclusion, but that's another matter.)

Closing.  Feel free to reopen if needed, with more details.
