### ISSUE TITLE
Add TOC to user guide, as well as links to top and permalink for each heading

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#89]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 07, 2010 16:22:27_

The user guide should have a table of contents.  In addition, each heading should have a link to the top and a permalink.  An example is:

<h3 id="editsummary>Edit Summary Message <a href="#editsummary">¶</a> - <a href="#toc">top</a></h3>

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=90_

**Comment by Sophivorus** [comment]
All documentation is now at Commons (https://commons.wikimedia.org/wiki/Help:Gadget-ProveIt) where the TOC is automatically generated by MediaWiki.
