### ISSUE TITLE
Allow inserting citations to RawReference

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#90]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 08, 2010 21:54:00_

Currently, you can not insert a citation to an existing RawReference, even if it already has a name.  Fixing this requires supporting citationStrings for this type.

This is related to issue 62 .  However, they can be implemented in either order.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=91_

**Comment by Sophivorus** [comment]
This will be accomplished at the same time as #232
