### ISSUE TITLE
Update configuration instructions for people using gadget

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#91]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on December 11, 2010 21:53:14_

Since gadgets load before the user's skin JavaScript (e.g. vector.js), configuration should now just be like (one or more of):

proveit.loadMaximized = true;
proveit.shouldAddSummary = false;

It seems to work in Firefox and Chrome (though the first time I tested in Chrome, it gave me an error about createGUI not being defined).  

But we need to test this in all our browsers, as well as continuing to provide instructions for people using importScript.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=92_

**Comment by lfschenone** [comment]
The latest version removed all configuration options. I think we should focus on keeping the gadget both simple and smart, so that configuration options are not necessary. Do you agree Matt?

**Comment by mattflaschen** [comment]
It's an open question.  I think after I deploy it, we should look at the feedback and consider whether to reintroduce preferences (in a more usable way).

I'll close this, since I don't think we're going to go the instruction route (if we did it, it would be some kind of UI).
