### ISSUE TITLE
Doesn't work in MacBook Firefox 3.68

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#93]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on January 04, 2011 15:23:44_

Perseus reports via the ProveIt talk page that ProveIt doesn't work in MacBook Firefox 3.68. http://en.wikipedia.org/w/index.php?title=User_talk:ProveIt_GT&action=historysubmit&diff=405747799&oldid=402910001 Needs to be confirmed.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=94_

**Comment by sophivorus** [comment]
The latest version of the gadget is too different for this report to still be relevant, and Firefox 3.68 is a VERY old version.
