### ISSUE TITLE
Documentation: Describe each type of reference for the USERS.

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#95]
_From [michaeloqu](https://code.google.com/u/106537379810745495028/) on January 10, 2011 05:44:05_

Now that Proveit is working, documenting -- or linking to documentation for -- each type of Cite Type needs to be done.  This is a usability issue, since it is not always obvious what each field within a citation type means.

I have a passion for usability of systems, and this would be a big improvement.  Leave a message on my talk page if you would like me to help with this.  ( http://en.wikipedia.org/wiki/User_talk:Michaeloqu )

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=96_

**Comment by sophivorus** [comment]
The TemplateData includes a description of each template and each parameter. The description for each parameter is now added to the interface as a tooltip (title attribute) to the label for that parameter, and the CSS cursor style "help" is applied to each label, so it's easy for users to notice the tooltip.
