### ISSUE TITLE
The [edit this reference] button does not appear for raw references

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#96]
_From [bobptz](https://code.google.com/u/115304658448898636038/) on January 31, 2011 07:49:37_

What steps will reproduce the problem? 1. just click on a reference in the ProveIt box.
2. Not all references will have the [edit this reference] What is the expected output? What do you see instead? I expected to see the [edit this reference] button.  I see it for very few references, not all of them. What version of the product are you using? On what operating system? I guess the latest version of proveit, on Windows XP, SP3.  Firefox 3.6.13 and IE 8.0.6001.18702. Please provide any additional information below. article: http://en.wikipedia.org/wiki/Antonio_Arnaiz-Villena On this reference, proveit works fine:
<ref>{{cite news | url = http://observer.guardian.co.uk/international/story/0,6903,605798,00.html | title = Journal axes gene research on Jews and Palestinians | work=The Observer | publisher = [[The Guardian]] | date = 25 November 2001 | author = Robin McKie }}</ref>

On this reference, proveit DOES NOT WORK:
<ref>Antonio Arnaiz-Villena, Nagah Elaiwa, Carlos Silvera, Ahmed Rostom, Juan Moscoso, Eduardo Gómez-Casado, Luis Allende, Pilar Varela, and Jorge Martínez-Laso,   [ http://kinoko.c.u-tokyo.ac.jp/~duraid/stolen_science/The_Origin_of_Palestinians_and_Their_Genetic_Relatedness_With_Other_Mediterranean_Populations.pdf The Origin of Palestinians and Their Genetic Relatedness_With Other Mediterranean Populations], ''Human Immunology'' 62 (2001), 889-900)</ref>

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=97_

**Comment by sophivorus** [comment]
The new interface has now [edit this reference] button.
