### ISSUE TITLE
the tab collapses on "add a reference"

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#98]
_From [andrea.forte](https://code.google.com/u/111976518998190259562/) on February 12, 2011 07:29:12_

What steps will reproduce the problem? 1. edit a wp page with or without references 
2. click on the proveit tab
3. it sometimes initially pops open to view refs, but then when i click on "add a reference," the tab closes or remains closed and so there are no fields visible. What is the expected output? What do you see instead? I expect to see the tab expand from the bottom of the page and display the interface for adding a ref but it doesn't open (the little arrow turns so it seems to think it's opening) What version of the product are you using? On what operating system? Safari Version 5.0.3 (6533.19.4) Mac OSX 10.6.6
also happened in Firefox 3.6.13 Please provide any additional information below.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=99_

**Comment by sophivorus** [comment]
This refers to the previous version of ProveIt. The latest version doesn't have this bug.
